const levelOne = new Level(
    [
        new Cloud('../img/5_background/layers/4_clouds/2.png', -350),
        new Cloud('../img/5_background/layers/4_clouds/1.png', 200),
        new Cloud('../img/5_background/layers/4_clouds/2.png', 700),

        new Cloud('../img/5_background/layers/4_clouds/2.png', 1200),
        new Cloud('../img/5_background/layers/4_clouds/1.png', 1700),
        new Cloud('../img/5_background/layers/4_clouds/2.png', 2200),

        new Cloud('../img/5_background/layers/4_clouds/2.png', 2700),
        new Cloud('../img/5_background/layers/4_clouds/1.png', 3200),
        new Cloud('../img/5_background/layers/4_clouds/2.png', 3700),

        new Cloud('../img/5_background/layers/4_clouds/2.png', 4200),
        new Cloud('../img/5_background/layers/4_clouds/1.png', 4700),
        new Cloud('../img/5_background/layers/4_clouds/2.png', 5200),

        new Cloud('../img/5_background/layers/4_clouds/2.png', 5700),
    ],
    [
        new BackgroundObject('../img/5_background/layers/air.png', -719),
        new BackgroundObject('../img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('../img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('../img/5_background/layers/1_first_layer/2.png', -719),

        new BackgroundObject('../img/5_background/layers/air.png', 0),
        new BackgroundObject('../img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('../img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('../img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('../img/5_background/layers/air.png', 719),
        new BackgroundObject('../img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('../img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('../img/5_background/layers/1_first_layer/2.png', 719),

        new BackgroundObject('../img/5_background/layers/air.png', 719 * 2),
        new BackgroundObject('../img/5_background/layers/3_third_layer/1.png', 719 * 2),
        new BackgroundObject('../img/5_background/layers/2_second_layer/1.png', 719 * 2),
        new BackgroundObject('../img/5_background/layers/1_first_layer/1.png', 719 * 2),
        new BackgroundObject('../img/5_background/layers/air.png', 719 * 3),
        new BackgroundObject('../img/5_background/layers/3_third_layer/2.png', 719 * 3),
        new BackgroundObject('../img/5_background/layers/2_second_layer/2.png', 719 * 3),
        new BackgroundObject('../img/5_background/layers/1_first_layer/2.png', 719 * 3),

        new BackgroundObject('../img/5_background/layers/air.png', 719 * 4),
        new BackgroundObject('../img/5_background/layers/3_third_layer/1.png', 719 * 4),
        new BackgroundObject('../img/5_background/layers/2_second_layer/1.png', 719 * 4),
        new BackgroundObject('../img/5_background/layers/1_first_layer/1.png', 719 * 4),
        new BackgroundObject('../img/5_background/layers/air.png', 719 * 5),
        new BackgroundObject('../img/5_background/layers/3_third_layer/2.png', 719 * 5),
        new BackgroundObject('../img/5_background/layers/2_second_layer/2.png', 719 * 5),
        new BackgroundObject('../img/5_background/layers/1_first_layer/2.png', 719 * 5),

        new BackgroundObject('../img/5_background/layers/air.png', 719 * 6),
        new BackgroundObject('../img/5_background/layers/3_third_layer/1.png', 719 * 6),
        new BackgroundObject('../img/5_background/layers/2_second_layer/1.png', 719 * 6),
        new BackgroundObject('../img/5_background/layers/1_first_layer/1.png', 719 * 6),
        new BackgroundObject('../img/5_background/layers/air.png', 719 * 7),
        new BackgroundObject('../img/5_background/layers/3_third_layer/2.png', 719 * 7),
        new BackgroundObject('../img/5_background/layers/2_second_layer/2.png', 719 * 7),
        new BackgroundObject('../img/5_background/layers/1_first_layer/2.png', 719 * 7),
    ],
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new SmallChicken,
        new SmallChicken,
        new SmallChicken,
        new SmallChicken,
        new SmallChicken,
        new EndBoss(),
    ],
    [
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
    ],
    [
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
        new Coin(),
    ]
)